num1=float(input("Enter first number:"))
num2=float(input("Enter second number:"))
print("Addition", num1+num2)
print("subtraction", num1-num2)
print("mulltiplication", num1*num2)
print("division", num1/num2)